In [1]:
import numpy as np
from math import factorial
import sympy
from potentials import ArbitrarySymmetricPolynomialPotential
from trap_model import TrapModel, initial_adiabatic_split
x=sympy.Symbol('x')
Phi=np.sum([(factorial(n))
            *(np.power(x,(2*n))) for n in range(3)])
sympy.Derivative(Phi,x, evaluate=True)

8*x**3 + 2*x

In [2]:
import matplotlib.pyplot as plt
#plt.plot([model.V.calc_static_pot(x) for x in np.linspace(-.5, .5)])

In [3]:

V=ArbitrarySymmetricPolynomialPotential(np.random.rayleigh(scale=1e-7, size=(25)), 3)
model=TrapModel(V,4)
#model.calc_ion_eq_pos(verbose=True)
#model.V.calc_static_pot(np.array([2,3]))

INFO:potentials:25


In [4]:
V.coeffs

array([1.81439694e-07, 5.77675087e-08, 1.75559365e-07, 6.19848161e-08,
       5.57955900e-08, 2.03247246e-07, 1.76672550e-07, 1.69343391e-07,
       5.69265351e-08, 1.05406263e-07, 1.89842980e-07, 1.91086054e-07,
       8.34084981e-08, 6.29471475e-08, 1.51200107e-07, 5.52076578e-08,
       1.37405006e-07, 1.13257459e-07, 1.38406610e-07, 1.27329576e-07,
       1.27767896e-07, 9.70484340e-08, 7.63345138e-08, 2.21588818e-07,
       1.02899027e-07])

In [5]:
model.optimize_ion_pos(5e-6)

INFO:trap_model:[-12.21114154  -4.07038051   4.07038051  12.21114154]


Optimization terminated successfully.
         Current function value: 0.554967
         Iterations: 9
         Function evaluations: 10
         Gradient evaluations: 10
         Hessian evaluations: 9
Optimization terminated successfully.
         Current function value: 0.556756
         Iterations: 9
         Function evaluations: 10
         Gradient evaluations: 10
         Hessian evaluations: 9
Optimization terminated successfully.
         Current function value: 0.575734
         Iterations: 9
         Function evaluations: 10
         Gradient evaluations: 10
         Hessian evaluations: 9
Optimization terminated successfully.
         Current function value: 0.641012
         Iterations: 8
         Function evaluations: 9
         Gradient evaluations: 9
         Hessian evaluations: 8
Optimization terminated successfully.
         Current function value: 0.695294
         Iterations: 8
         Function evaluations: 9
         Gradient evaluations: 9
         Hessian eval

 This problem is unconstrained.
/home/davis/anaconda3/envs/iontraps/lib/python3.12/site-packages/scipy/optimize/_minimize.py:729: RuntimeWarning: A bad approximation caused failure to predict improvement.
  res = _minimize_trust_ncg(fun, x0, args, jac, hess, hessp,


         Current function value: -1006939292.417812
         Iterations: 37
         Function evaluations: 37
         Gradient evaluations: 35
         Hessian evaluations: 35
         Current function value: -1006939291.762809
         Iterations: 55
         Function evaluations: 41
         Gradient evaluations: 37
         Hessian evaluations: 37
         Current function value: -1006939278.344437
         Iterations: 37
         Function evaluations: 37
         Gradient evaluations: 35
         Hessian evaluations: 35
         Current function value: -1006939133.226307
         Iterations: 37
         Function evaluations: 37
         Gradient evaluations: 35
         Hessian evaluations: 35
         Current function value: -1006938172.823488
         Iterations: 53
         Function evaluations: 39
         Gradient evaluations: 36
         Hessian evaluations: 36
         Current function value: -1006933924.028599
         Iterations: 55
         Function evaluations: 41
     

KeyboardInterrupt: 

In [ ]:
np.mean(np.diff(model.ion_pos))

5.158722392576242e-06

In [ ]:
model.ion_pos

array([-7.73808359e-06, -2.79693382e-06,  2.79693382e-06,  7.73808359e-06])

In [ ]:
model.calc_modes()

Optimization terminated successfully.
         Current function value: 0.555240
         Iterations: 9
         Function evaluations: 10
         Gradient evaluations: 10
         Hessian evaluations: 9


(array([ 550108.68468799,  884657.47214848, 1511775.82392585,
        1515909.60731288]),
 array([[ 0.13681352,  0.14592488,  0.69374495,  0.69188578],
        [ 0.69374495,  0.69188578, -0.13681352, -0.14592488],
        [ 0.69374495, -0.69188578, -0.13681352,  0.14592488],
        [ 0.13681352, -0.14592488,  0.69374495, -0.69188578]]),
 array([3000000.        , 2979646.95249991, 2936596.91403625,
        2915312.66540784]),
 array([[ 0.5       ,  0.6306288 ,  0.5       ,  0.31985514],
        [ 0.5       ,  0.31985514, -0.5       , -0.6306288 ],
        [ 0.5       , -0.31985514, -0.5       ,  0.6306288 ],
        [ 0.5       , -0.6306288 ,  0.5       , -0.31985514]]))

In [ ]:
model.calc_ion_eq_pos()

Optimization terminated successfully.
         Current function value: 0.555240
         Iterations: 9
         Function evaluations: 10
         Gradient evaluations: 10
         Hessian evaluations: 9


array([-7.73808359e-06, -2.79693382e-06,  2.79693382e-06,  7.73808359e-06])

In [ ]:
from trap_model import initial_adiabatic_split
list_=initial_adiabatic_split(4,20,2,10e-6,4,5e-6,3)
list_

In [1]:
from potentials import ArbitrarySymmetricPolynomialPotential
from trap_model import TrapModel
import numpy as np
V=ArbitrarySymmetricPolynomialPotential(np.random.rayleigh(1e-8, (26)), 3)
model=TrapModel(V, 4)
model.optimize_ion_pos_for_symmetric_split(np.array([2.5e-6, 7.5e-6,]), verbose=False)
model.optimize_ion_pos_for_symmetric_split(np.array([5.0e-6, 10e-6,]), verbose=False)
model.ion_pos

INFO:potentials:26
INFO:trap_model:[-8.99992842e-06 -3.24832923e-06  3.24832923e-06  8.99992842e-06]
INFO:trap_model:[-8.99986796e-06 -3.24825517e-06  3.24825517e-06  8.99986796e-06]
INFO:trap_model:[-8.99800905e-06 -3.24740216e-06  3.24740216e-06  8.99800905e-06]
INFO:trap_model:[-8.97831742e-06 -3.24096843e-06  3.24096843e-06  8.97831742e-06]
INFO:trap_model:[-8.89801715e-06 -3.21184778e-06  3.21184778e-06  8.89801715e-06]
INFO:trap_model:[-8.72129933e-06 -3.15033147e-06  3.15033147e-06  8.72129933e-06]
INFO:trap_model:[-8.54884379e-06 -3.08915354e-06  3.08915354e-06  8.54884379e-06]
INFO:trap_model:[-8.47837204e-06 -3.06473709e-06  3.06473709e-06  8.47837204e-06]
INFO:trap_model:[-8.50935179e-06 -3.07605369e-06  3.07605369e-06  8.50935179e-06]
INFO:trap_model:[-8.60309802e-06 -3.10920150e-06  3.10920150e-06  8.60309802e-06]
INFO:trap_model:[-8.72350143e-06 -3.15135101e-06  3.15135101e-06  8.72350143e-06]
INFO:trap_model:[-8.83778252e-06 -3.19128919e-06  3.19128919e-06  8.83778252e-0

array([-1.04685323e-05, -3.83563991e-06,  3.83563991e-06,  1.04685323e-05])

In [4]:
np.mean(np.diff(model.ion_pos))

4.954182139608162e-06